package com.laviavi.adsbandroid.enrich

/**
 * Operator name from the 3-letter ICAO airline prefix of a callsign.
 *
 * Generated from the Python receiver's `enrich/lookup.py:_AIRLINE_MAP` by
 * `tools/gen_airlines.py` — edit the table there and regenerate, do not hand-edit
 * this file. Offline and free: the prefix is already inside the decoded callsign,
 * so no lookup of any kind is required.
 *
 * A callsign only carries an operator when it is a flight-number callsign
 * ("UAL2184"). General-aviation aircraft transmit their registration as the
 * callsign ("N38901"), which has no operator and correctly returns null.
 */
object Airlines {

    /** Operator name for a flight-number callsign, or null if the prefix is unknown. */
    fun fromCallsign(callsign: String?): String? {
        val cs = callsign?.trim()?.uppercase() ?: return null
        if (cs.length < 3) return null
        return MAP[cs.substring(0, 3)]
    }

    /** True when the callsign is the aircraft's own registration, not a flight number. */
    fun isRegistrationCallsign(callsign: String?): Boolean {
        val cs = callsign?.trim()?.uppercase() ?: return false
        return cs.length >= 2 && cs[0] == 'N' && cs[1].isDigit()
    }

    val size: Int get() = MAP.size

    private val MAP: Map<String, String> = mapOf(
        "AAL" to "American Airlines",
        "AAR" to "Asiana Airlines",
        "ACA" to "Air Canada",
        "AFR" to "Air France",
        "AIC" to "Air India",
        "AIJ" to "Air Inuit",
        "AJM" to "Air Arabia",
        "AKX" to "HK Express",
        "ALK" to "SriLankan Airlines",
        "AMX" to "Aeromexico",
        "ANA" to "All Nippon Airways",
        "ANZ" to "Air New Zealand",
        "APJ" to "Peach Aviation",
        "APW" to "Air Peace",
        "ARG" to "Aerolineas Argentinas",
        "ASA" to "Alaska Airlines",
        "ASH" to "Mesa Airlines",
        "ATI" to "Air Transport International",
        "AVA" to "Avianca",
        "AXM" to "AirAsia",
        "AYY" to "Air Yucatan",
        "AZA" to "ITA Airways",
        "AZU" to "Azul Brazilian Airlines",
        "BAW" to "British Airways",
        "BCS" to "European Air Transport",
        "BEL" to "Brussels Airlines",
        "BER" to "Air Berlin",
        "BTI" to "Air Baltic",
        "BWA" to "Caribbean Airlines",
        "CAL" to "China Airlines",
        "CCA" to "Air China",
        "CEB" to "Cebu Pacific",
        "CFG" to "Condor",
        "CHH" to "Hainan Airlines",
        "CJT" to "Cargojet",
        "CLX" to "Cargolux",
        "CMB" to "Brussels Airlines Cargo",
        "CMP" to "Copa Airlines",
        "CNA" to "China Northern Airlines",
        "CSN" to "China Southern Airlines",
        "CSZ" to "Shenzhen Airlines",
        "CXA" to "Xiamen Airlines",
        "CYP" to "Cyprus Airways",
        "DAL" to "Delta Air Lines",
        "DHL" to "DHL Aviation",
        "DLA" to "Air Dolomiti",
        "DLH" to "Lufthansa",
        "EAL" to "Eastern Air Lines",
        "EIN" to "Aer Lingus",
        "EJA" to "NetJets",
        "ELY" to "El Al",
        "ETA" to "Ethiopian Airlines",
        "ETD" to "Etihad Airways",
        "EVA" to "EVA Air",
        "EXS" to "Jet2",
        "EZY" to "easyJet",
        "FDX" to "FedEx Express",
        "FFT" to "Frontier Airlines",
        "FIN" to "Finnair",
        "FJI" to "Fiji Airways",
        "FLY" to "Flybe",
        "GEC" to "Lufthansa Cargo",
        "GFA" to "Gulf Air",
        "GIA" to "Garuda Indonesia",
        "GLO" to "Gol Transportes",
        "HAL" to "Hawaiian Airlines",
        "HDA" to "Dragonair",
        "HVN" to "Vietnam Airlines",
        "IBE" to "Iberia",
        "ICE" to "Icelandair",
        "IGO" to "IndiGo",
        "IRR" to "Iran Air",
        "ISR" to "Israir",
        "JAI" to "IndiGo",
        "JAL" to "Japan Airlines",
        "JAT" to "Air Serbia",
        "JBU" to "JetBlue Airways",
        "JET" to "Bmi Regional",
        "JSA" to "JetSmart",
        "JST" to "Jetstar",
        "KAL" to "Korean Air",
        "KLM" to "KLM Royal Dutch",
        "KQA" to "Kenya Airways",
        "LAM" to "LAM Mozambique",
        "LAN" to "LATAM Airlines",
        "LAP" to "LATAM Paraguay",
        "LDA" to "Lauda",
        "LGL" to "Luxair",
        "LNE" to "Jungle Air",
        "LOT" to "LOT Polish Airlines",
        "LRC" to "LACSA",
        "MAS" to "Malaysia Airlines",
        "MAU" to "Air Mauritius",
        "MGL" to "MIAT Mongolian",
        "MSR" to "EgyptAir",
        "MXD" to "Mexicana",
        "NAX" to "Norwegian Air",
        "NKS" to "Spirit Airlines",
        "NWA" to "Northwest Airlines",
        "OAL" to "Olympic Air",
        "OMA" to "Oman Air",
        "PAC" to "Polar Air Cargo",
        "PAL" to "Philippine Airlines",
        "PIA" to "Pakistan International",
        "PKT" to "Batik Air",
        "QFA" to "Qantas",
        "QME" to "Qantas",
        "QQE" to "AirAsia X",
        "QTR" to "Qatar Airways",
        "RAM" to "Royal Air Maroc",
        "RBA" to "Royal Brunei",
        "RJA" to "Royal Jordanian",
        "ROT" to "TAROM",
        "RPA" to "Republic Airways",
        "RYR" to "Ryanair",
        "SAA" to "South African Airways",
        "SAB" to "Sabena",
        "SAS" to "Scandinavian Airlines",
        "SAW" to "SaudiArabia Airlines",
        "SBI" to "S7 Airlines",
        "SCO" to "SmartWings",
        "SEY" to "Air Seychelles",
        "SIA" to "Singapore Airlines",
        "SKW" to "SkyWest Airlines",
        "SLM" to "Surinam Airways",
        "SQC" to "Singapore Airlines Cargo",
        "SRK" to "Sunrock",
        "SVA" to "Saudia",
        "SWA" to "Southwest Airlines",
        "SWR" to "Swiss International",
        "TAM" to "LATAM Brasil",
        "TAP" to "TAP Air Portugal",
        "TFL" to "Arkefly",
        "TGW" to "Scoot",
        "THA" to "Thai Airways",
        "THY" to "Turkish Airlines",
        "TOM" to "TUI Airways",
        "TSC" to "Air Transat",
        "TUI" to "TUI fly",
        "TVF" to "Transavia France",
        "TWA" to "Trans World Airlines",
        "TWY" to "T'way Air",
        "UAE" to "Emirates",
        "UAL" to "United Airlines",
        "UIA" to "Ukraine International",
        "UPS" to "UPS Airlines",
        "USA" to "US Airways",
        "VIR" to "Virgin Atlantic",
        "VJC" to "VietJet Air",
        "VLG" to "Vueling",
        "VOE" to "Volotea",
        "VRD" to "Virgin America",
        "WJA" to "WestJet",
        "WZZ" to "Wizz Air",
        "XAX" to "Xtra Airways",
    )
}
