package com.laviavi.adsbandroid

import com.laviavi.adsbandroid.crc.CrcChecker
import com.laviavi.adsbandroid.crc.IcaoCache
import com.laviavi.adsbandroid.decoder.MessageDecoder
import com.laviavi.adsbandroid.decoder.RawFrame
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

/**
 * Differential test against the Python reference implementation (adsb_v9_5).
 *
 * Both implementations are replayed over the same 467 real frames captured from
 * this antenna (DF 0/4/5/11/16/17/18/20/24), in the same order, through their own
 * ICAO cache — so parity-address recovery depends on the same history in both.
 * `fixtures/python_reference.tsv` is generated by `scratchpad/ref_compare.py`.
 *
 * Any divergence here is a real behavioural difference from the reference, not a
 * style difference: this is the check that the Kotlin port actually agrees.
 */
class PythonParityTests {

    private data class Expected(val frame: String, val crc: String, val recovered: String, val decoded: String)

    private fun loadExpected(): List<Expected> {
        val text = javaClass.getResourceAsStream("/fixtures/python_reference.tsv")
            ?.bufferedReader()?.readText()
            ?: error("python_reference.tsv fixture missing — regenerate with ref_compare.py")
        return text.lineSequence()
            .drop(1)
            .filter { it.isNotBlank() }
            .map { line ->
                val f = line.split("\t")
                Expected(f[0], f[1], f[2], f[3])
            }.toList()
    }

    private fun hex(s: String) = IntArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16) }

    /** Replays the fixture through the Kotlin chain exactly as the pipeline would. */
    private fun runKotlin(expected: List<Expected>): List<Expected> {
        val cache = IcaoCache()
        val decoder = MessageDecoder()
        return expected.map { e ->
            val checked = CrcChecker.check(RawFrame(hex(e.frame)), correctSingleBit = true, icaoCache = cache)
            val accepted = checked.crcResult == CrcChecker.CrcResult.VALID ||
                checked.crcResult == CrcChecker.CrcResult.CORRECTED ||
                checked.crcResult == CrcChecker.CrcResult.RECOVERED
            val decodedIcao = if (accepted) {
                decoder.decode(checked)?.icao?.let { String.format("%06X", it) } ?: "-"
            } else "-"
            Expected(
                frame = e.frame,
                crc = checked.crcResult.name,
                recovered = checked.recoveredIcao?.let { String.format("%06X", it) } ?: "-",
                decoded = decodedIcao,
            )
        }
    }

    /**
     * The one intentional divergence from the reference, kept because it is
     * demonstrably correct (see `CrcParityTests.Df11InterrogatorId`).
     *
     * For DF11, the trailing field is PI = CRC(data) XOR II, so the syndrome
     * `CRC(data) XOR PI` is the interrogator ID — a small number, which is why
     * dump1090 accepts a residual under 80 from a known aircraft. Kotlin's
     * `computeCrc` returns exactly that syndrome. The Python reference's
     * `remainder` is instead `crc24(whole_frame)`, which is 0 for a valid frame
     * but is *not* the II code when non-zero (e.g. II=7 surfaces as 0xFFD024).
     * Its `remainder < 80` branch therefore effectively never fires, and it
     * discards genuine DF11 replies that carry a non-zero interrogator ID.
     */
    private fun isKnownDf11IidDivergence(e: Expected, a: Expected): Boolean {
        val df = hex(e.frame)[0] shr 3
        if (df != 11) return false
        val syndrome = CrcChecker.computeCrc(hex(e.frame))
        return e.crc == "INVALID" && a.crc == "VALID" && syndrome in 1..79
    }

    @Test fun `CRC outcome matches the Python reference except the documented DF11 case`() {
        val expected = loadExpected()
        val actual = runKotlin(expected)
        val unexplained = expected.indices
            .filter { expected[it].crc != actual[it].crc && !isKnownDf11IidDivergence(expected[it], actual[it]) }
            .map { "${expected[it].frame} (DF${hex(expected[it].frame)[0] shr 3}): python=${expected[it].crc} kotlin=${actual[it].crc}" }
        assertTrue(unexplained.isEmpty(),
            "Unexplained CRC divergence on ${unexplained.size}/${expected.size} frames:\n" +
                unexplained.take(15).joinToString("\n"))

        val agreed = expected.indices.count { expected[it].crc == actual[it].crc }
        assertTrue(agreed > expected.size * 0.9,
            "Only $agreed/${expected.size} frames agreed — divergence is wider than the documented case")
    }

    @Test fun `recovered ICAO matches the Python reference exactly`() {
        val expected = loadExpected()
        val actual = runKotlin(expected)
        val mismatches = expected.indices
            .filter { expected[it].recovered != actual[it].recovered }
            .map { "${expected[it].frame}: python=${expected[it].recovered} kotlin=${actual[it].recovered}" }
        assertTrue(mismatches.isEmpty(),
            "Recovered-ICAO divergence on ${mismatches.size} frames:\n" + mismatches.take(15).joinToString("\n"))
    }

    @Test fun `decoded ICAO matches the Python reference except the documented DF11 case`() {
        val expected = loadExpected()
        val actual = runKotlin(expected)
        val unexplained = expected.indices
            .filter { expected[it].decoded != actual[it].decoded && !isKnownDf11IidDivergence(expected[it], actual[it]) }
            .map { "${expected[it].frame} (DF${hex(expected[it].frame)[0] shr 3}): python=${expected[it].decoded} kotlin=${actual[it].decoded}" }
        assertTrue(unexplained.isEmpty(),
            "Unexplained decoded-ICAO divergence on ${unexplained.size} frames:\n" +
                unexplained.take(15).joinToString("\n"))
    }

    @Test fun `fixture actually exercises parity-address recovery`() {
        // Guards the test itself: if the fixture lost its AP frames this suite
        // would pass trivially while covering nothing that regressed.
        val expected = loadExpected()
        assertTrue(expected.count { it.crc == "RECOVERED" } > 10, "Fixture must contain RECOVERED frames")
        assertTrue(expected.count { it.crc == "VALID" } > 50, "Fixture must contain VALID frames")
        assertTrue(expected.count { it.crc == "PARITY_ADDRESS" } > 10, "Fixture must contain unverifiable AP frames")
    }
}
