#!/usr/bin/env python3
"""
Generate core/receiver/.../enrich/Airlines.kt from two sources:

1. The Python receiver's `enrich/lookup.py:_AIRLINE_MAP` (the behavioral
   reference at --python-root, read-only — never edited by this script).
2. OpenFlights' airlines.dat (cached locally at tools/openflights_airlines.dat,
   ODbL-licensed: https://openflights.org — refresh with
   `curl -o tools/openflights_airlines.dat \\
     https://raw.githubusercontent.com/jpatokal/openflights/master/data/airlines.dat`),
   filtered to active airlines with a real 3-letter ICAO code.

_AIRLINE_MAP always wins on a conflicting ICAO prefix — it's the
already-verified-against-real-traffic table; OpenFlights only fills gaps it
doesn't cover. Re-run after changing the Python table or refreshing the cache.

    python tools/gen_airlines.py --python-root D:/SDR/adsb_v9_5
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

OUT = Path("core/receiver/src/main/kotlin/com/laviavi/adsbandroid/enrich/Airlines.kt")
OPENFLIGHTS_DAT = Path("tools/openflights_airlines.dat")

# airlines.dat columns: AirlineID,Name,Alias,IATA,ICAO,Callsign,Country,Active
OPENFLIGHTS_ICAO_COL = 4
OPENFLIGHTS_NAME_COL = 1
OPENFLIGHTS_ACTIVE_COL = 7


def load_openflights(path: Path) -> dict[str, str]:
    """ICAO -> name for active airlines with a real 3-letter ICAO code."""
    if not path.exists():
        return {}
    result: dict[str, str] = {}
    with open(path, encoding="utf-8", newline="") as fh:
        for row in csv.reader(fh):
            if len(row) <= max(OPENFLIGHTS_ICAO_COL, OPENFLIGHTS_NAME_COL, OPENFLIGHTS_ACTIVE_COL):
                continue
            if row[OPENFLIGHTS_ACTIVE_COL] != "Y":
                continue
            icao = row[OPENFLIGHTS_ICAO_COL].strip().upper()
            # Real ICAO airline designators are 3 ASCII A-Z letters (ICAO Doc
            # 8585) — a decoded Mode S callsign can't contain anything else,
            # so a non-ASCII code (a handful of OpenFlights rows have e.g.
            # Cyrillic) can never match and is just dead weight in the table.
            if len(icao) != 3 or not (icao.isascii() and icao.isalpha()):
                continue
            name = row[OPENFLIGHTS_NAME_COL].strip()
            if not name or name in ("Unknown", "Private flight"):
                continue
            result.setdefault(icao, name)
    return result


HEADER = '''package com.laviavi.adsbandroid.enrich

/**
 * Operator name from the 3-letter ICAO airline prefix of a callsign.
 *
 * Generated by `tools/gen_airlines.py` from two sources — edit there and
 * regenerate, do not hand-edit this file:
 *  - the Python receiver's `enrich/lookup.py:_AIRLINE_MAP` (verified against
 *    real traffic; wins on any conflict);
 *  - OpenFlights' airlines.dat (ODbL license — https://openflights.org),
 *    filling in ICAO prefixes the reference table doesn't cover.
 * Offline and free either way: the prefix is already inside the decoded
 * callsign, so no lookup of any kind is required.
 *
 * A callsign only carries an operator when it is a flight-number callsign
 * ("UAL2184"). General-aviation aircraft transmit their registration as the
 * callsign ("N38901"), which has no operator and correctly returns null.
 */
object Airlines {

    /** Operator name for a flight-number callsign, or null if the prefix is unknown. */
    fun fromCallsign(callsign: String?): String? {
        val cs = callsign?.trim()?.uppercase() ?: return null
        if (cs.length < 3) return null
        return MAP[cs.substring(0, 3)]
    }

    /** True when the callsign is the aircraft's own registration, not a flight number. */
    fun isRegistrationCallsign(callsign: String?): Boolean {
        val cs = callsign?.trim()?.uppercase() ?: return false
        return cs.length >= 2 && cs[0] == 'N' && cs[1].isDigit()
    }

    val size: Int get() = MAP.size

    private val MAP: Map<String, String> = mapOf(
'''

FOOTER = '''    )
}
'''


def kotlin_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--python-root", required=True)
    ap.add_argument("--openflights-dat", default=str(OPENFLIGHTS_DAT))
    args = ap.parse_args(argv)

    sys.path.insert(0, str(Path(args.python_root).resolve()))
    from adsb_receiver.enrich.lookup import _AIRLINE_MAP as reference_table

    openflights_table = load_openflights(Path(args.openflights_dat))
    added = {k: v for k, v in openflights_table.items() if k not in reference_table}
    table = {**openflights_table, **reference_table}  # reference_table wins on conflict

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER)
        for prefix in sorted(table):
            fh.write(f'        "{prefix}" to "{kotlin_string(table[prefix])}",\n')
        fh.write(FOOTER)

    print(
        f"wrote {OUT} — {len(table)} airlines "
        f"({len(reference_table)} reference + {len(added)} from OpenFlights)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
