#!/usr/bin/env python3
"""
Capture the Python receiver's ICAO -> registration output for the whole US civil
block so the Kotlin port can be checked against it exactly.

Emitting all 915,399 rows would mean a 12 MB fixture in the repo. Instead the
generator streams every address through a SHA-256 and commits the digest, plus
every 997th row (997 is prime, so the sample does not align with the trie's
powers-of-ten stem boundaries) and every boundary address.

The digest is the real test: Kotlin recomputes it over the same range, so a
single differing address anywhere in the block fails. The sampled rows exist only
to make a failure diagnosable instead of just red.

    python tools/gen_registration_parity.py --python-root D:/SDR/adsb_v9_5
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

OUT = Path("core/receiver/src/test/resources/fixtures/registration_parity.tsv")
US_MIN, US_MAX = 0xA00001, 0xADF7C7
SAMPLE_STRIDE = 997

# Stem edges: first/last of the block, and the first address of each digit count.
BOUNDARIES = [
    0xA00001, 0xA00002, 0xA00003, 0xA0001A, 0xA0001B,
    0xA00727, 0xA00728, 0xA0A4C1, 0xA12345, 0xADF7C7,
]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--python-root", required=True)
    args = ap.parse_args(argv)

    sys.path.insert(0, str(Path(args.python_root).resolve()))
    from adsb_receiver.enrich.registration import icao_to_registration

    digest = hashlib.sha256()
    samples: list[tuple[str, str]] = []
    count = 0

    for value in range(US_MIN, US_MAX + 1):
        icao = format(value, "06X")
        reg = icao_to_registration(icao)
        if reg is None:
            print(f"ERROR: Python returned None for in-block {icao}", file=sys.stderr)
            return 1
        digest.update(f"{icao}\t{reg}\n".encode("ascii"))
        count += 1
        if value % SAMPLE_STRIDE == 0 or value in BOUNDARIES:
            samples.append((icao, reg))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(f"# generated by tools/gen_registration_parity.py\n")
        fh.write(f"# every address {US_MIN:06X}..{US_MAX:06X} hashed as 'ICAO\\tREG\\n'\n")
        fh.write(f"#count\t{count}\n")
        fh.write(f"#sha256\t{digest.hexdigest()}\n")
        fh.write("icao\tregistration\n")
        for icao, reg in samples:
            fh.write(f"{icao}\t{reg}\n")

    print(f"wrote {OUT}")
    print(f"  {count:,} addresses hashed -> {digest.hexdigest()}")
    print(f"  {len(samples):,} sampled rows committed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
